dist: xenial
sudo: false
language: node_js
node_js:
  - node
install:
  - npm install
  - npm install firebase-tools
script:
  - npm run test
  - npm run coverage
  - npm run build
  - firebase deploy --token "$FIREBASE_TOKEN"
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - olelashaw@gmail.com
    on_failure: always
